### ISSUE TITLE
Stencil module consumption not working

### ISSUE THREAD

**Issue by rblin081** [rgst-io/stencil#144]
Following the instructions from https://stencil.rgst.io/guide/basic-module.html, here's my notes from each step.

### Step 1 - Create the stencil module
```
mkdir helloworld; cd helloworld
helloworld % stencil create module github.com/yourorg/helloworld
INFO stencil 0.9.0
INFO Fetching dependencies
INFO Loading native extensions
INFO Rendering templates
INFO Writing template(s) to disk
INFO Running post-run command(s)
helloworld % ls
stencil.lock    stencil.yaml
```

Between steps 1 and 2 I'd expect the templates directory to be created automatically, I can't think of a scenario where there wouldn't be templates for a module.  Moving on...

### Step 2 - Create a template in the module
```
mkdir templates
helloworld % echo 'print("Hello World")' > hello_world.py
helloworld % ls  
hello_world.py  stencil.lock    stencil.yaml
```

### Step 3 - Create the consuming application
```
% mkdir testapp; cd testapp
testapp % cat >stencil.yaml <<EOF
name: testapp
modules:
  - name: github.com/yourorg/helloworld

replacements:
  # Replace ../helloworld with the path to your module.
  github.com/yourorg/helloworld: ../helloworld
EOF
testapp % stencil
INFO stencil 0.9.0
INFO Fetching dependencies
ERRO failed to run error="open ../helloworld/manifest.yaml: no such file or directory"
```

Again I'd expect a `manifest.yaml` to be generated from `stencil create module`. Constructing a simplified manifest using https://github.com/rgst-io/stencil-golang/blob/e2ea9a1980f765f668d4a42d1f9108db777bf86d/manifest.yaml as an example

**helloworld/manifest.yaml**
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/rgst-io/stencil/main/schemas/manifest.jsonschema.json
name: github.com/yourorg/helloworld
type: templates,extension
```

Trying again...
```
testapp % stencil
INFO stencil 0.9.0
INFO Fetching dependencies
INFO  -> github.com/yourorg/helloworld 
INFO Loading native extensions
ERRO failed to run error="failed to load extensions from module \"github.com/yourorg/helloworld\": failed to create connection to extension: fork/exec ../helloworld/bin/plugin: no such file or directory"
```

This is where I'm unsure to progress. `rgst-io/stencil-goloang` [GitHub](https://github.com/rgst-io/stencil-golang/tree/e2ea9a1980f765f668d4a42d1f9108db777bf86d) doesn't have a `/bin` and I'm unsure how it's generated

**Comment by jaredallard** [comment]
Sorry for the trouble again :sob:

`stencil create module` used to create everything, butttt as we forked it parts got cleaned up as we separated from Outreach. 

The issue here right now is `type` being set to both `templates,extension`. Since you're not writing a native extension right now, you can actually remove the `type` field altogether. That should resolve this problem

**Comment by jaredallard** [comment]
As for the `bin` directory, for the local development process of a stencil _native extension_, it will look for `bin/plugin` as the binary to run.

That used to be created automatically with the plugin framework we had (and will be again when I get that created on the rgst-io org).

So, if you end up implementing a native extension ([following these docs](https://stencil.rgst.io/guide/basic-native-extension.html)), you'll end up compiling the binary (via `go build`, if using Go) to `bin/plugin`.

**Comment by rblin081** [comment]
Hmm unfortunately still not seeing this work.

After modifying `helloworld/manifest.yaml` to 
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/rgst-io/stencil/main/schemas/manifest.jsonschema.json
name: github.com/yourorg/helloworld
```

with a directory structure of
```
helloworld/
   templates/
        hello_world.py
   manifest.yaml
   stencil.yaml
   stencil.lock
```


From `test-app`
```
testapp % ls
stencil.lock    stencil.yaml
testapp % stencil
INFO stencil 0.9.0
INFO Fetching dependencies
INFO  -> github.com/yourorg/helloworld 
INFO Loading native extensions
INFO Rendering templates
INFO Writing template(s) to disk
INFO Running post-run command(s)
testapp % ls
stencil.lock    stencil.yamltestapp % 
```

Not receiving an error anymore (yay) but also not seeing an files be rendered from the template(s)

**Comment by jaredallard** [comment]
@rblin081 I'm assuming from your other issue that you got past this, am I right? 👀
